import {
  adoptionApplicationStatuses,
  adoptionStatusOptions,
  ageGroupOptions,
  housingOptions,
  neuterStatusOptions,
  projectStatusOptions,
  sexOptions,
  shelterKindOptions,
  speciesOptions,
} from "@/lib/options";
import type { Option, ResourceConfig } from "./types";

/*
 * Panelde yönetilen her bölüm burada tanımlanır.
 * Yeni bir bölüm eklemek = Supabase'de tablo + buraya bir kayıt.
 * Liste, ekleme, düzenleme ve silme ekranları otomatik oluşur.
 */

export const membershipStatuses: Option[] = [
  { value: "yeni", label: "Yeni" },
  { value: "inceleniyor", label: "İnceleniyor" },
  { value: "kabul", label: "Kabul edildi" },
  { value: "red", label: "Reddedildi" },
];

export const suggestionKinds: Option[] = [
  { value: "istek", label: "İstek" },
  { value: "oneri", label: "Öneri" },
  { value: "sikayet", label: "Şikâyet" },
  { value: "tesekkur", label: "Teşekkür" },
];

export const suggestionStatuses: Option[] = [
  { value: "yeni", label: "Yeni" },
  { value: "okundu", label: "Okundu" },
  { value: "cozuldu", label: "Çözüldü" },
];

/** Kenar menüdeki grupların sırası */
export const resourceGroups = ["Kulüp", "Patili Dostlar", "Çalışmalarımız", "Gelen kutusu"];

const sortOrderField = {
  name: "sort_order",
  label: "Sıra",
  type: "number" as const,
  half: true,
  defaultValue: 0,
  help: "Küçük sayı önce görünür.",
};
const publishedField = { name: "is_published", label: "Sitede göster", type: "boolean" as const, defaultValue: true };
const publishedColumn = { name: "is_published", label: "Yayında", type: "boolean" as const };

export const resources: ResourceConfig[] = [
  // ------------------------------------------------------------------ Kulüp
  {
    slug: "ekip",
    table: "team_members",
    label: "Yönetim Ekibi",
    singular: "Ekip üyesi",
    description: "Ekibimiz sayfasında görünen kişiler.",
    icon: "users",
    group: "Kulüp",
    kind: "content",
    orderBy: [
      { column: "sort_order", ascending: true },
      { column: "created_at", ascending: true },
    ],
    titleField: "name",
    publicPath: "/ekibimiz",
    columns: [
      { name: "photo_url", label: "", type: "image" },
      { name: "name", label: "Ad Soyad" },
      { name: "role", label: "Görev" },
      { name: "sort_order", label: "Sıra" },
      publishedColumn,
    ],
    fields: [
      { name: "name", label: "Ad Soyad", type: "text", required: true, half: true },
      { name: "role", label: "Görev", type: "text", half: true, placeholder: "Örn: Başkan" },
      { name: "department", label: "Bölüm / sınıf", type: "text", half: true },
      { ...sortOrderField, help: "Küçük sayı önce görünür. Başkan için 1 yaz." },
      { name: "photo_url", label: "Fotoğraf", type: "image" },
      { name: "bio", label: "Kısa tanıtım", type: "textarea", rows: 4 },
      { name: "instagram_url", label: "Instagram", type: "url", half: true },
      { name: "linkedin_url", label: "LinkedIn", type: "url", half: true },
      publishedField,
    ],
  },
  {
    slug: "etkinlikler",
    table: "events",
    label: "Etkinlikler",
    singular: "Etkinlik",
    description: "Etkinlikler sayfası ve ana sayfadaki geri sayım.",
    icon: "calendar",
    group: "Kulüp",
    kind: "content",
    orderBy: [{ column: "starts_at", ascending: false }],
    titleField: "title",
    publicPath: "/etkinlikler",
    columns: [
      { name: "cover_url", label: "", type: "image" },
      { name: "title", label: "Başlık" },
      { name: "starts_at", label: "Tarih", type: "datetime" },
      { name: "location", label: "Yer" },
      publishedColumn,
    ],
    fields: [
      { name: "title", label: "Etkinlik adı", type: "text", required: true },
      { name: "starts_at", label: "Başlangıç", type: "datetime", required: true, half: true },
      { name: "ends_at", label: "Bitiş", type: "datetime", half: true, help: "İsteğe bağlı." },
      { name: "location", label: "Yer", type: "text", half: true },
      {
        name: "registration_url",
        label: "Kayıt / bilgi bağlantısı",
        type: "url",
        half: true,
        help: "Varsa Google Form vb.",
      },
      { name: "cover_url", label: "Kapak görseli", type: "image" },
      { name: "description", label: "Açıklama", type: "textarea", rows: 6 },
      publishedField,
    ],
  },

  // --------------------------------------------------------- Patili Dostlar
  {
    slug: "sahiplendirme",
    table: "adoptions",
    label: "Sahiplendirme",
    singular: "İlan",
    description: 'Yuva arayan dostlarımız. Sahiplenilince durumu "Yuvasını buldu" yap, mutlu sonlarda görünsün.',
    icon: "heart",
    group: "Patili Dostlar",
    kind: "content",
    orderBy: [
      { column: "sort_order", ascending: true },
      { column: "created_at", ascending: false },
    ],
    titleField: "name",
    publicPath: "/sahiplendirme",
    columns: [
      { name: "cover_url", label: "", type: "image" },
      { name: "name", label: "Adı" },
      { name: "species", label: "Tür" },
      { name: "status", label: "Durum" },
      publishedColumn,
    ],
    fields: [
      { name: "name", label: "Adı", type: "text", required: true, half: true },
      {
        name: "status",
        label: "Durum",
        type: "select",
        options: adoptionStatusOptions,
        required: true,
        defaultValue: "sahiplendirilebilir",
        half: true,
      },
      {
        name: "species",
        label: "Tür",
        type: "select",
        options: speciesOptions,
        required: true,
        defaultValue: "kedi",
        half: true,
      },
      { name: "sex", label: "Cinsiyet", type: "select", options: sexOptions, half: true },
      { name: "age_group", label: "Yaş grubu", type: "select", options: ageGroupOptions, half: true },
      { name: "age_text", label: "Yaşı", type: "text", half: true, placeholder: "Örn: yaklaşık 2 yaşında" },
      { name: "cover_url", label: "Kapak fotoğrafı", type: "image" },
      { name: "photos", label: "Diğer fotoğraflar", type: "images" },
      {
        name: "traits",
        label: "Karakteri",
        type: "text",
        placeholder: "oyuncu, uysal, kucak seven",
        help: "Virgülle ayır; sitede etiket olarak görünür.",
      },
      { name: "description", label: "Hikâyesi / tanıtım", type: "textarea", rows: 5 },
      { name: "vaccinated", label: "Aşıları yapıldı", type: "boolean", half: true },
      { name: "neutered", label: "Kısırlaştırıldı", type: "boolean", half: true },
      { name: "health_notes", label: "Sağlık notları", type: "textarea", rows: 2 },
      { name: "location", label: "Bulunduğu yer", type: "text", half: true, placeholder: "Örn: Geçici yuvada" },
      sortOrderField,
      publishedField,
    ],
  },
  {
    slug: "iyilesenler",
    table: "rescue_stories",
    label: "İyileştirdiklerimiz",
    singular: "Hikâye",
    description: "Tedavi ettiğimiz dostların önce/sonra fotoğrafları ve hikâyeleri.",
    icon: "heart-pulse",
    group: "Patili Dostlar",
    kind: "content",
    orderBy: [
      { column: "sort_order", ascending: true },
      { column: "rescued_on", ascending: false },
    ],
    titleField: "name",
    publicPath: "/iyilestirdiklerimiz",
    columns: [
      { name: "after_url", label: "", type: "image" },
      { name: "name", label: "Adı" },
      { name: "summary", label: "Özet" },
      publishedColumn,
    ],
    fields: [
      { name: "name", label: "Adı", type: "text", required: true, half: true },
      {
        name: "species",
        label: "Tür",
        type: "select",
        options: speciesOptions,
        required: true,
        defaultValue: "kedi",
        half: true,
      },
      { name: "before_url", label: "Önce (bulunduğu hâli)", type: "image", half: true },
      { name: "after_url", label: "Sonra (iyileşmiş hâli)", type: "image", half: true },
      {
        name: "summary",
        label: "Kısa özet",
        type: "text",
        placeholder: "Örn: Kırık patisiyle bulundu, şimdi koşuyor!",
      },
      { name: "story", label: "Hikâyesi", type: "textarea", rows: 6 },
      { name: "photos", label: "Diğer fotoğraflar", type: "images" },
      { name: "rescued_on", label: "Kurtarıldığı tarih", type: "date", half: true },
      sortOrderField,
      publishedField,
    ],
  },
  {
    slug: "veterinerler",
    table: "vets",
    label: "Anlaşmalı Veterinerler",
    singular: "Veteriner",
    description: "Anlaşmalı klinikler; konum girilirse haritada da görünür.",
    icon: "stethoscope",
    group: "Patili Dostlar",
    kind: "content",
    orderBy: [
      { column: "sort_order", ascending: true },
      { column: "name", ascending: true },
    ],
    titleField: "name",
    publicPath: "/veterinerler",
    columns: [
      { name: "logo_url", label: "", type: "image" },
      { name: "name", label: "Klinik" },
      { name: "phone", label: "Telefon" },
      publishedColumn,
    ],
    fields: [
      { name: "name", label: "Klinik adı", type: "text", required: true, half: true },
      { name: "doctor_name", label: "Veteriner hekim", type: "text", half: true },
      { name: "phone", label: "Telefon", type: "tel", half: true },
      {
        name: "working_hours",
        label: "Çalışma saatleri",
        type: "text",
        half: true,
        placeholder: "Hafta içi 09:00–19:00",
      },
      {
        name: "discount_info",
        label: "Anlaşma / indirim",
        type: "text",
        placeholder: "Örn: Kulüp hayvanlarına %30 indirim",
      },
      { name: "services", label: "Hizmetler", type: "textarea", rows: 2, help: "Kısırlaştırma, aşı, cerrahi…" },
      { name: "address", label: "Adres", type: "textarea", rows: 2 },
      {
        name: "location",
        label: "Haritadaki konumu",
        type: "location",
        latField: "lat",
        lngField: "lng",
        help: "Haritaya tıkla ya da Google Maps bağlantısını yapıştır. Boş bırakılırsa haritada görünmez.",
      },
      {
        name: "maps_url",
        label: "Yol tarifi bağlantısı",
        type: "url",
        half: true,
        help: "Google Maps paylaş bağlantısı.",
      },
      { name: "website_url", label: "Web sitesi / Instagram", type: "url", half: true },
      { name: "logo_url", label: "Logo / fotoğraf", type: "image" },
      { name: "is_emergency", label: "7/24 acil hizmet veriyor", type: "boolean" },
      sortOrderField,
      publishedField,
    ],
  },
  {
    slug: "yuvalar",
    table: "shelter_locations",
    label: "Yuva & Besleme Noktaları",
    singular: "Nokta",
    description: "Haritada görünen mama, su, kulübe ve yuva noktaları.",
    icon: "map-pin",
    group: "Patili Dostlar",
    kind: "content",
    orderBy: [
      { column: "kind", ascending: true },
      { column: "name", ascending: true },
    ],
    titleField: "name",
    publicPath: "/yuvalar",
    columns: [
      { name: "photo_url", label: "", type: "image" },
      { name: "name", label: "Adı" },
      { name: "kind", label: "Tür" },
      publishedColumn,
    ],
    fields: [
      { name: "name", label: "Adı", type: "text", required: true, half: true, placeholder: "Örn: Kütüphane önü" },
      {
        name: "kind",
        label: "Tür",
        type: "select",
        options: shelterKindOptions,
        required: true,
        defaultValue: "besleme",
        half: true,
      },
      {
        name: "location",
        label: "Konum",
        type: "location",
        latField: "lat",
        lngField: "lng",
        required: true,
        help: 'Noktanın yanındaysan "Konumumu kullan" düğmesine bas.',
      },
      { name: "description", label: "Açıklama", type: "textarea", rows: 3 },
      { name: "responsible", label: "Sorumlu gönüllü", type: "text", half: true },
      { name: "photo_url", label: "Fotoğraf", type: "image" },
      publishedField,
    ],
  },

  // --------------------------------------------------------- Çalışmalarımız
  {
    slug: "kisirlastirma",
    table: "neuter_records",
    label: "Kısırlaştırma",
    singular: "Kısırlaştırma kaydı",
    description: "Planlananlar sitede takvimde, yapılanlar sayaçta görünür.",
    icon: "scissors",
    group: "Çalışmalarımız",
    kind: "content",
    orderBy: [{ column: "scheduled_on", ascending: false }],
    listSelect: "*, vets(name)",
    titleField: "animal_name",
    publicPath: "/kisirlastirma",
    columns: [
      { name: "photo_url", label: "", type: "image" },
      { name: "animal_name", label: "Adı" },
      { name: "scheduled_on", label: "Tarih", type: "date" },
      { name: "status", label: "Durum" },
      { name: "vets.name", label: "Veteriner" },
      publishedColumn,
    ],
    fields: [
      {
        name: "animal_name",
        label: "Adı",
        type: "text",
        required: true,
        half: true,
        placeholder: "Örn: Tekir (isimsiz)",
      },
      {
        name: "status",
        label: "Durum",
        type: "select",
        options: neuterStatusOptions,
        required: true,
        defaultValue: "planlandi",
        half: true,
        help: 'Operasyon bitince "Yapıldı" yap; sayaç artar.',
      },
      { name: "scheduled_on", label: "Tarih", type: "date", required: true, half: true },
      {
        name: "vet_id",
        label: "Veteriner",
        type: "relation",
        relation: { table: "vets", labelField: "name" },
        half: true,
        help: "Listede yoksa önce Anlaşmalı Veterinerler'e ekle.",
      },
      {
        name: "species",
        label: "Tür",
        type: "select",
        options: speciesOptions,
        required: true,
        defaultValue: "kedi",
        half: true,
      },
      { name: "sex", label: "Cinsiyet", type: "select", options: sexOptions, half: true },
      { name: "area", label: "Bulunduğu bölge", type: "text", placeholder: "Örn: Mühendislik fakültesi önü" },
      { name: "photo_url", label: "Fotoğraf", type: "image" },
      { name: "note", label: "Not", type: "textarea", rows: 2, help: "Sitede görünür." },
      publishedField,
    ],
  },
  {
    slug: "projeler",
    table: "projects",
    label: "Projelerimiz",
    singular: "Proje",
    description: "Kulübün yürüttüğü projeler ve ilerleme durumları.",
    icon: "folder-kanban",
    group: "Çalışmalarımız",
    kind: "content",
    orderBy: [
      { column: "sort_order", ascending: true },
      { column: "created_at", ascending: false },
    ],
    titleField: "title",
    publicPath: "/projeler",
    columns: [
      { name: "cover_url", label: "", type: "image" },
      { name: "title", label: "Proje" },
      { name: "status", label: "Durum" },
      { name: "progress", label: "İlerleme %" },
      publishedColumn,
    ],
    fields: [
      { name: "title", label: "Proje adı", type: "text", required: true },
      {
        name: "status",
        label: "Durum",
        type: "select",
        options: projectStatusOptions,
        required: true,
        defaultValue: "devam",
        half: true,
      },
      {
        name: "progress",
        label: "İlerleme (%)",
        type: "number",
        min: 0,
        max: 100,
        defaultValue: 0,
        half: true,
        help: "0 ile 100 arası.",
      },
      { name: "summary", label: "Kısa özet", type: "text", help: "Kartlarda görünür." },
      { name: "cover_url", label: "Kapak görseli", type: "image" },
      { name: "description", label: "Ayrıntılı anlatım", type: "textarea", rows: 8 },
      { name: "photos", label: "Fotoğraflar", type: "images" },
      { name: "started_on", label: "Başlangıç", type: "date", half: true },
      { name: "finished_on", label: "Bitiş", type: "date", half: true },
      sortOrderField,
      publishedField,
    ],
  },
  {
    slug: "borclar",
    table: "debts",
    label: "Borçlar",
    singular: "Borç",
    description: 'Destek Ol sayfasında şeffaflık için gösterilir. Ödeme yaptıkça "Ödenen" tutarı güncelle.',
    icon: "wallet",
    group: "Çalışmalarımız",
    kind: "content",
    orderBy: [
      { column: "sort_order", ascending: true },
      { column: "incurred_on", ascending: false },
    ],
    titleField: "creditor",
    publicPath: "/destek",
    columns: [
      { name: "receipt_url", label: "", type: "image" },
      { name: "creditor", label: "Alacaklı" },
      { name: "amount", label: "Tutar", type: "money" },
      { name: "paid_amount", label: "Ödenen", type: "money" },
      publishedColumn,
    ],
    fields: [
      {
        name: "creditor",
        label: "Kime borçluyuz?",
        type: "text",
        required: true,
        placeholder: "Örn: Can Veteriner Kliniği",
      },
      {
        name: "description",
        label: "Ne için?",
        type: "textarea",
        rows: 2,
        placeholder: "Örn: 3 kedinin kırık tedavisi",
      },
      { name: "amount", label: "Toplam tutar (₺)", type: "number", step: 0.01, min: 0, required: true, half: true },
      {
        name: "paid_amount",
        label: "Ödenen (₺)",
        type: "number",
        step: 0.01,
        min: 0,
        defaultValue: 0,
        half: true,
      },
      { name: "incurred_on", label: "Borç tarihi", type: "date", half: true },
      { name: "due_on", label: "Son ödeme tarihi", type: "date", half: true },
      {
        name: "receipt_url",
        label: "Fatura / dekont fotoğrafı",
        type: "image",
        help: "Şeffaflık için sitede gösterilir.",
      },
      sortOrderField,
      publishedField,
    ],
  },
  {
    slug: "ihtiyaclar",
    table: "needs",
    label: "İhtiyaç Listesi",
    singular: "İhtiyaç",
    description: "Destek Ol sayfasındaki mama, kum, ilaç listesi.",
    icon: "list-checks",
    group: "Çalışmalarımız",
    kind: "content",
    orderBy: [
      { column: "is_fulfilled", ascending: true },
      { column: "sort_order", ascending: true },
      { column: "created_at", ascending: false },
    ],
    titleField: "title",
    publicPath: "/destek",
    columns: [
      { name: "title", label: "İhtiyaç" },
      { name: "quantity", label: "Miktar" },
      { name: "is_urgent", label: "Acil", type: "flag" },
      { name: "is_fulfilled", label: "Karşılandı", type: "flag" },
      publishedColumn,
    ],
    fields: [
      {
        name: "title",
        label: "Ne lazım?",
        type: "text",
        required: true,
        half: true,
        placeholder: "Örn: Yavru kedi maması",
      },
      { name: "quantity", label: "Miktar", type: "text", half: true, placeholder: "Örn: 10 kg" },
      { name: "description", label: "Açıklama", type: "textarea", rows: 2 },
      { name: "is_urgent", label: "Acil", type: "boolean", half: true },
      { name: "is_fulfilled", label: "Karşılandı", type: "boolean", half: true, help: "Listede üstü çizili görünür." },
      sortOrderField,
      publishedField,
    ],
  },

  // ------------------------------------------------------------ Gelen kutusu
  {
    slug: "uyelik-basvurulari",
    table: "membership_applications",
    label: "Üyelik Başvuruları",
    singular: "Başvuru",
    description: "Kulübe Katıl formundan gelenler.",
    icon: "id-card",
    group: "Gelen kutusu",
    kind: "inbox",
    orderBy: [{ column: "created_at", ascending: false }],
    titleField: "full_name",
    columns: [
      { name: "full_name", label: "Ad Soyad" },
      { name: "department", label: "Bölüm" },
      { name: "created_at", label: "Tarih", type: "datetime" },
      { name: "status", label: "Durum", type: "status" },
    ],
    fields: [
      { name: "full_name", label: "Ad Soyad", type: "text" },
      { name: "email", label: "E-posta", type: "email" },
      { name: "phone", label: "Telefon", type: "tel" },
      { name: "student_no", label: "Öğrenci no", type: "text" },
      { name: "department", label: "Bölüm", type: "text" },
      { name: "grade", label: "Sınıf", type: "text" },
      { name: "interests", label: "İlgi alanları", type: "textarea" },
      { name: "message", label: "Mesaj", type: "textarea" },
    ],
    status: { field: "status", options: membershipStatuses, newValue: "yeni" },
  },
  {
    slug: "sahiplenme-basvurulari",
    table: "adoption_applications",
    label: "Sahiplenme Başvuruları",
    singular: "Sahiplenme başvurusu",
    description: "İlan sayfalarındaki formdan gelenler.",
    icon: "hand-heart",
    group: "Gelen kutusu",
    kind: "inbox",
    orderBy: [{ column: "created_at", ascending: false }],
    titleField: "full_name",
    columns: [
      { name: "full_name", label: "Ad Soyad" },
      { name: "animal_name", label: "Dost" },
      { name: "created_at", label: "Tarih", type: "datetime" },
      { name: "status", label: "Durum", type: "status" },
    ],
    fields: [
      { name: "animal_name", label: "Sahiplenmek istediği", type: "text" },
      { name: "full_name", label: "Ad Soyad", type: "text" },
      { name: "phone", label: "Telefon", type: "tel" },
      { name: "email", label: "E-posta", type: "email" },
      { name: "city", label: "Şehir / semt", type: "text" },
      { name: "housing", label: "Yaşadığı yer", type: "select", options: housingOptions },
      { name: "other_pets", label: "Evdeki diğer hayvanlar", type: "textarea" },
      { name: "experience", label: "Deneyimi", type: "textarea" },
      { name: "message", label: "Mesajı", type: "textarea" },
    ],
    status: { field: "status", options: adoptionApplicationStatuses, newValue: "yeni" },
  },
  {
    slug: "oneriler",
    table: "suggestions",
    label: "İstek & Öneriler",
    singular: "Mesaj",
    description: "İstek ve öneri köşesinden gelenler.",
    icon: "message",
    group: "Gelen kutusu",
    kind: "inbox",
    orderBy: [{ column: "created_at", ascending: false }],
    titleField: "message",
    columns: [
      { name: "message", label: "Mesaj" },
      { name: "kind", label: "Tür" },
      { name: "name", label: "Gönderen" },
      { name: "created_at", label: "Tarih", type: "datetime" },
      { name: "status", label: "Durum", type: "status" },
    ],
    fields: [
      { name: "kind", label: "Tür", type: "select", options: suggestionKinds },
      { name: "name", label: "Gönderen", type: "text" },
      { name: "email", label: "E-posta", type: "email" },
      { name: "message", label: "Mesaj", type: "textarea" },
    ],
    status: { field: "status", options: suggestionStatuses, newValue: "yeni", openedValue: "okundu" },
  },
];

export function getResource(slug: string) {
  return resources.find((resource) => resource.slug === slug);
}

export function optionLabel(options: Option[] | undefined, value: unknown) {
  return options?.find((option) => option.value === value)?.label ?? String(value ?? "");
}
